kind: PersistentVolume
apiVersion: v1
metadata:
  name: urb-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/urb"
#    path: "path_template"
