apiVersion: v1
kind: Service
metadata:
  name: marathonsvc
spec:
  type: LoadBalancer
  ports:
    - port: 8080
#      targetPort: 8080
  selector:
    app: marathonsvc
#  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: marathonsvc
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: marathonsvc
    spec:
      containers:
        - image: local/urb-marathon
          name: marathonsvc
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c", "/usr/bin/marathon --master urb://urb-master:6379 --zk zk://zoo-svc:2181/marathon"]
          env:
            - name: MESOS_NATIVE_JAVA_LIBRARY
              value: /urb/lib/liburb.so
#            - name: URB_LOGLEVEL
#              value: 0
#            - name: GLOG_v
#              value: 2
          ports:
            - containerPort: 8080
              name: marathonsvc
