VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.boot_timeout = 10
  config.ssh.insert_key = false
  config.vm.define "build-machine", autostart: true do |app|
    app.vm.hostname = "head.private"
    if ENV['URB_K8S']
      app.vm.synced_folder "../..", "/scratch/urb"
    else
      app.vm.synced_folder "..", "/scratch/urb"
    end
    app.vm.provision "puppet" do |puppet|
      puppet.options = "--verbose"
      puppet.hiera_config_path = "puppet/hiera.yaml"
      puppet.manifests_path = "puppet"
      puppet.manifest_file  = "default.pp"
    end
    app.vm.provider "docker" do |d|
      d.image = "urb-build"
      d.name = "urb-build"
      d.has_ssh = true
      d.create_args = [ "--privileged", "-v", "/sys/fs/cgroup:/sys/fs/cgroup:ro" ]
    end
  end
end
