# Copyright 2017 Univa Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.boot_timeout = 10
  config.ssh.insert_key = false
  if ENV['SYNCED_FOLDER']
    synced_folder = ENV['SYNCED_FOLDER']
  else
    synced_folder = ".."
  end
  vm_name = File.basename(Pathname.new(Dir.pwd + "/" + synced_folder).realpath) + "-build"
  config.vm.define "urb-build", autostart: true do |app|
    app.vm.synced_folder synced_folder, "/scratch/urb"
    app.vm.hostname = "head.private"
    app.vm.provision "shell" do |shell|
      shell.inline = "/opt/puppetlabs/bin/puppet apply /vagrant/puppet/default.pp"
    end
    app.vm.provider "docker" do |d|
      d.image = "urb-build"
      d.name = vm_name
      if ENV['DOCKER_SUFFIX']
        d.name += ENV['DOCKER_SUFFIX']
      end
      d.has_ssh = true
      d.create_args = [ "--privileged", "-v", "/sys/fs/cgroup:/sys/fs/cgroup:ro" ]
    end
  end
end
