apiVersion: batch/v1
kind: Job
metadata:
  name: urb-exec
spec:
  template:
    metadata:
      name: urb-exec
    spec:
      containers:
        - name: urb-executor-runner
          image: local/urb-executor-runner
          imagePullPolicy: IfNotPresent
          env:
            - name: JOB_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      restartPolicy: Never 
