apiVersion: batch/v1
kind: Job
metadata:
  name: urb-exec
spec:
  template:
    metadata:
      name: urb-exec
    spec:
      # reference to volume claim will be removed by adapter if PV doesn't exist
      volumes:
        - name: urb-pv-storage
          persistentVolumeClaim:
            claimName: urb-pvc
      containers:
        - name: urb-executor-runner
          image: local/urb-executor-runner
          imagePullPolicy: IfNotPresent
          env:
            - name: JOB_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          # mount will be removed by adapter if PV doesn't exist
          volumeMounts:
            - mountPath: "/opt"
              name: urb-pv-storage
      restartPolicy: Never 
