apiVersion: v1
kind: Service
metadata:
  name: urb-singularity
spec:
  type: NodePort
  ports:
    - port: 7099
      nodePort: 32099
  selector:
    app: urb-singularity
#  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: urb-singularity
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: urb-singularity
    spec:
      containers:
      - image: hubspot/singularityservice
        name: urb-singularity
        imagePullPolicy: IfNotPresent
        env:
        - name: SINGULARITY_MESOS_MASTER
          value: urb-master:5060
        - name: SINGULARITY_ZK
          value: zoo-svc:2181
        ports:
        - containerPort: 7099
          name: urb-singularity
