apiVersion: v1
kind: Service
metadata:
  name: urb-master
spec:
  type: NodePort
  ports:
    - port: 6379
      name: native-api
    - port: 5060
      name: http-api
  selector:
    app: urb-master
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: urb-master
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: urb-master
    spec:
      containers:
      - image: local/urb-redis
        name: urb-redis
        imagePullPolicy: IfNotPresent
      - image: local/urb-service
        name: urb-service
        imagePullPolicy: IfNotPresent
#        resources:
#          requests:
#            cpu: "1"
        ports:
        - containerPort: 6379
          name: urb-service
        - containerPort: 5060
          name: urb-http-sch
        - containerPort: 5061
          name: urb-http-exe
        env:
        - name: URB_ROOT
          value: /urb
        - name: URB_CONFIG_FILE
          value: $(URB_ROOT)/etc/urb.conf
        - name: URB_MASTER
          value: urb://urb-master:6379
        - name: URB_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - mountPath: /urb/etc
          name: urb-config
      volumes:
        - name: urb-config
          configMap:
            name: urb-config
            items:
            - key: urb.conf
              path: urb.conf
